### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by betzrhodes**
- fixed ADC conversion bug, all getters that use ADC conversion are now async
- shortened function names
- shortened parameter table slot names
- code refactor
- added tests to cover async cases
- updated current tests 
- updated docs 
- updated version

### CODE REVIEW

**Comment by betzrhodes** [comment]
All examples in readme and example folder have been tested and run on an impC001 breakout.

**Review by smittytone — APPROVED** [review]

**Comment by smittytone** [comment]
Can we change the setting *setChargeTerminationCurrentLimit* to just *terminationCurrent* or what *chargeTerminationCurrent*, since we're moving up to 3.0.0? See the BQ24595 PR for rationale

**Comment by imp-jdillon** [comment]
Recommend changing getChargeVoltage() to getChargeTerminationVoltage() to better reflect its operation

**Comment by betzrhodes** [comment]
Made a big breaking change - shortened function and setting names. I've updated code/tests/readme. Please double check me.

**Comment by zandr** [comment]
Re: [71b9ca7](https://github.com/electricimp/BQ25895/pull/2/commits/71b9ca75fa55b6bd91e82fd910fad53303534601), I'm not sure what we're trying to be consistent with? That change is neither consistent with the part datasheet (it's REG0A, not REG.0A), nor other libraries (where register names are constants).

**Pull request merged**
