### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by betzrhodes**
Initial release, driver based on v1.0.0 of BQ25895M. 
- Support for default settings on both BQ25895 and BQ25895M

Changes based on BQ25895M v1.0.0 include: 
- Updated enable method parameters (breaking change)
- Added enable setting option to set charge termination current
- Added tests
- Added method to get input status
- Disabled watchdog, so settings will persist through sleep cycles
   - Removed watchdog timer and kick watchdog, as they are not longer needed
- Updated docs to reference BQ25895 and BQ25895M support
- Updated example
- Updated version number
- Updated license date

### CODE REVIEW

**Comment by betzrhodes** [comment]
For better idea of updates see https://github.com/electricimp/BQ25895M/compare/feature/default_settings

**Comment by betzrhodes** [comment]
@zandr & @smittytone -
I think this is ready for release. Most of this has been reviewed in the BQ25895M repo. I've got tests passing, so this is more a sanity check that I've caught everything in the copy/paste.

**Comment by zandr** [comment]
Setting it up on real hardware now, as a final sanity check.

**Comment by zandr** [comment]
Should the actual squirrel file be named without the 'M'?

**Comment by betzrhodes** [comment]
Yes! Good catch.

**Pull request merged**
